### ISSUE TITLE
Number of characters in SQLStatement is longer than 65536 error in cloud log

### ISSUE THREAD

**Issue by SergeyShurygin** [reimagined/resolve-cloud#62]
it was in https://r3ffio75qhm4aa2ag2t1ev2tjov1.resolve.sh/

**Comment by MrCheater** [comment]
Event is too large to save.

**CAUSE**
Amazon RDS Data Service Quotas and Limits

https://docs.aws.amazon.com/rdsdataservice/latest/APIReference/API_ExecuteStatement.html#API_ExecuteStatement_RequestSyntax

Maximum length of 65536.

**SOLUTION**
Reduce the amount of content so that the size of the event is less than 64 KB.
